# Generated by Django 5.1.4 on 2025-01-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmin',
            name='face_image',
            field=models.ImageField(default='exit', upload_to='face_image'),
            preserve_default=False,
        ),
    ]
