# Generated by Django 5.1.4 on 2025-05-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
        ('service', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='service.service'),
        ),
    ]
