# Generated by Django 5.1.4 on 2025-04-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.CharField(blank=True, max_length=300, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('linkedin', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('youtube', models.TextField(blank=True, null=True)),
                ('twitter', models.TextField(blank=True, null=True)),
                ('github', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_setting_favicon/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_setting_logo/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_setting_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='site_setting_videos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='site_setting_resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
