# Generated by Django 5.1.4 on 2025-04-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Site_setting',
        ),
    ]
